import audiVideo from "@assets/minigifs/audi-city-lab-miniloop.mp4";
import biennaleVideo from "@assets/minigifs/venice-biennale-2023-miniloop.mp4";
import cityOfPlantsVideo from "@assets/minigifs/city-of-plants-miniloop.mp4";
import gardenOfMomentsVideo from "@assets/minigifs/garden-of-moments-miniloop.mp4";
import plaidElexVideo from "@assets/minigifs/plaid-elex-miniloop.mp4";
import jekkaVideo from "@assets/minigifs/airplane-instrument-miniloop.mp4";
import postpostVideo from "@assets/minigifs/post-post-miniloop.mp4";
import tedVideo from "@assets/minigifs/tedx-sf-miniloop.mp4";
import summerVideo from "@assets/minigifs/plaid-35-summers-miniloop.mp4";
import mazdaVideo from "@assets/minigifs/mazda-miniloop.mp4";
import dianaVideo from "@assets/minigifs/plaid-diana-miniloop.mp4";
import stoveVideo from "@assets/minigifs/playing-stove-miniloop.mp4";
import fieldOfInstrumentsVideo from "@assets/minigifs/field-of-instruments-miniloop.mp4";
import mogeesPro1Video from "@assets/minigifs/mogees-pro-1-miniloop.mp4";
import mogeesPro2Video from "@assets/minigifs/mogees-pro-2-miniloop.mp4";
import mogeesPlayAppsVideo from "@assets/minigifs/mogees-play-apps-miniloop.mp4";

export interface Project {
  id: string;
  title: string;
  subtitle?: string;
  location: string;
  category: "Art" | "Installations" | "Products";
  videoUrl: string;
  description: string;
  credits?: string;
  thumbnailVideo?: string;
  thumbnailImage?: string;
}

export const projects: Project[] = [
  {
    id: "field-of-instruments",
    title: "Field of Instruments",
    subtitle: "La Défense, Paris",
    location: "Paris",
    category: "Installations",
    videoUrl: "local:field-of-instruments",
    description: "Public installation composed of 21 metallic sound instruments distributed across an open urban space.\n\nEach instrument responds to touch, scraping, and percussive gestures, producing sound through tuned physical interactions. The instruments operate as a collective system: individual actions generate discrete sonic events that interlock into a coherent, continuously evolving composition. The spatial arrangement encourages distributed participation, allowing multiple performers to play simultaneously while maintaining overall harmonic stability.\n\nCommissioned by Lynk & Co. Music by Michele Tadini.",
    thumbnailVideo: fieldOfInstrumentsVideo
  },
  {
    id: "audi-city-lab",
    title: "Fifth Ring",
    subtitle: "Milan Design Week",
    location: "Milan",
    category: "Installations",
    videoUrl: "local:audi-city-lab",
    description: "Fifth Ring is an interactive installation that treats architecture as a responsive instrument. Piazza del Quadrilatero in Milan is temporarily flooded with a shallow layer of water, transforming the ground into a reflective surface and a medium for interaction.\n\nVibration sensors embedded in the wooden catwalk detect human movement and contact. As visitors walk through the space, their vibrations generate sound and light responses, translating physical motion into a continuously evolving audiovisual composition. Reflections, ripples, and sound remain tightly coupled, making each action immediately perceptible across multiple senses.\n\nRather than separating spectators from the work, Fifth Ring turns the entire space into an interface. Every movement contributes to the system, producing a collective composition shaped by the presence and behavior of its visitors.\n\nFifth Ring explores how public spaces can shift from static settings to living systems—spaces that listen, respond, and are activated through shared physical experience.\n\nBy MAD Architects and Bruno Zamborlin for Audi.",
    thumbnailVideo: audiVideo
  },
  {
    id: "city-of-plants",
    title: "City of Plants",
    subtitle: "Venice Biennale",
    location: "Venice",
    category: "Art",
    videoUrl: "local:city-of-plants",
    description: "City of Plants is an interactive installation that brings plants, humans, and algorithms into a shared sensory system. The work consists of three enclosed spheres, each hosting a living plant ecosystem. Throughout the nine months of the Venice Biennale, the plants were sustained indoors through artificial lighting and automated watering, allowing the ecosystems to remain alive and responsive over the entire duration of the exhibition.\n\nEach sphere integrates environmental sensors, sound synthesis, and light. Plant bio-signals are continuously translated into evolving sound and visual responses, forming an ambient layer generated by the plants themselves.\n\nWithin each ecosystem, pebbles are embedded as points of human interaction. By touching or moving them, visitors trigger discrete musical events. These sounds are algorithmically tuned to remain in harmonic relationship with the plant-generated audio, ensuring that human intervention does not override the system but enters into dialogue with it.\n\nThe resulting composition is never fixed and has no single author. Plants, visitors, and algorithms operate on the same level, contributing equally to a continuously evolving environment of sound and light.\n\nRather than representing nature, City of Plants treats plants as active entities capable of perception and response. Vibrations, data, and movement function as a shared language through which different forms of intelligence co-compose a fragile, responsive ecology.\n\nInteractive installation by MAD Architects and Bruno Zamborlin. Music by Michele Tadini.",
    thumbnailVideo: cityOfPlantsVideo
  },
  {
    id: "post-post",
    title: "Post Post",
    subtitle: "Jerusalem",
    location: "Jerusalem",
    category: "Installations",
    videoUrl: "local:post-post",
    description: "Post Post is a site-specific interactive installation that reconfigures a public square as a space for collective play and composition. A series of colored postal boxes are transformed into continuous tactile interfaces, responsive to how they are touched rather than simply activated.\n\nEach box translates gesture and contact into sound, producing variations that are never repeated in the same way. The resulting audio continuously changes in response to the quality and duration of each interaction. In parallel, corresponding light patterns unfold across the façade of the central postal building.\n\nThe system is designed so that multiple simultaneous interactions remain musically coherent. When several participants engage with the boxes at the same time (intentionally or at random) the sounds adapt and harmonize, forming a collective composition rather than a set of isolated triggers.\n\nPost Post encourages exploration, attentive listening, and shared authorship. Familiar urban objects become expressive interfaces, and the square itself operates as a temporary instrument played by its visitors.\n\nInteractive installation by Yuvi Gerstein, Shuli Oded, and Bruno Zamborlin.",
    credits: undefined,
    thumbnailVideo: postpostVideo
  },
  {
    id: "venice-biennale-2023",
    title: "BelMondo Tracks",
    subtitle: "Venice Biennale",
    location: "Venice",
    category: "Art",
    videoUrl: "https://www.youtube.com/watch?v=EOGTSC-pW5w",
    description: "A project documenting the BelMondo Tracks initiative in Calabria's abandoned Belmonte castle garden. The work combines light architectural interventions and the creation of interactive sound furniture to encourage community listening and engagement. Vibrations from revitalization activities were transformed into musical instruments for the installation. Partnership with Orizzontale architecture. Music composition by Michele Tadini. Interactive installation at Italian Pavilion featuring a living room with vibration sensors. Explores relational practices and digital tools with a view to playfulness and active listening.",
    thumbnailVideo: biennaleVideo
  },
  {
    id: "plaid-elex",
    title: "ELEX",
    subtitle: "Music video with Plaid",
    location: "London",
    category: "Art",
    videoUrl: "local:plaid-elex",
    description: "Music collaboration between Bruno Zamborlin and Plaid (Warp records)",
    thumbnailVideo: plaidElexVideo
  },
  {
    id: "garden-of-moments",
    title: "Garden of Moments",
    subtitle: "AlUla",
    location: "Al Ula",
    category: "Installations",
    videoUrl: "local:garden-of-moments",
    description: "Garden of Moments is a multisensory installation situated in the desert landscape of Al Ula. At its center stands a semi-spherical sculptural structure whose surface integrates tactile textures designed to be touched and explored.\n\nSurrounding the sculpture are eight seats, each functioning as an interactive instrument. Through touch and presence, visitors activate sound and light responses, contributing to a shared composition that unfolds in real time. Individual gestures remain perceptible, yet the system encourages listening, coordination, and collective participation rather than isolated interaction.\n\nThe installation operates as a space for pause and attention. Sound, light, and touch are tightly coupled, allowing participants to perceive their actions as part of a larger temporal and spatial whole.\n\nGarden of Moments explores how public installations can foster moments of shared presence and deep listening, using interaction not as spectacle but as a means of connection.\n\nInteraction and sound design by Bruno Zamborlin.",
    credits: "Designer/Producer: Balich Wonder Studio. Creative Direction/Design: Marco Klefisch. Interaction & Sound Design: Bruno Zamborlin. Music Composition: Michele Tadini. Lighting Design: D'alesio & Santoro.",
    thumbnailVideo: gardenOfMomentsVideo
  },
  {
    id: "airplane-instrument",
    title: "Aircraft as Instrument",
    subtitle: "Moscow",
    location: "Moscow",
    category: "Installations",
    videoUrl: "local:airplane-instrument",
    description: "Soviet airplane Yak-42 became the biggest music instrument in this music video for singer-songwriter Jekka.",
    thumbnailVideo: jekkaVideo
  },
  {
    id: "plaid-35-summers",
    title: "35 Summers (live)",
    subtitle: "Performance with Plaid",
    location: "RoundHouse (London)",
    category: "Art",
    videoUrl: "local:plaid-35-summers",
    description: "Performing 35 Summers live at the London RoundHouse for Imogen Heap's Reverb festival",
    thumbnailVideo: summerVideo
  },
  {
    id: "mazda",
    title: "Automotive as Instrument",
    subtitle: "Commercial work",
    location: "London",
    category: "Products",
    videoUrl: "https://www.youtube.com/watch?v=QlCNhOm3cCs",
    description: "Playing a Mazda car Commercial video and interactive installation for SXSW",
    thumbnailVideo: mazdaVideo
  },
  {
    id: "plaid-diana",
    title: "Diana (live)",
    subtitle: "Performance with Plaid",
    location: "Turin",
    category: "Art",
    videoUrl: "https://www.youtube.com/watch?v=o95Momw3-vA",
    description: "Performable sound sculpture, featured as part of MTV Digital Days at Galleria di Diana, Venaria Palace, Turin.",
    thumbnailVideo: dianaVideo
  },
  {
    id: "mogees-pro",
    title: "Mogees Pro",
    subtitle: "Product",
    location: "London",
    category: "Products",
    videoUrl: "local:mogees-pro-1",
    description: "Mogees was a hardware sensor and companion app developed between 2013 and 2017 to turn any physical surface of any shape or size into a playable musical instrument. By attaching the sensor to everyday objects, users could transform tables, walls, glass, or metal into expressive, interactive sound interfaces accessible to everyone, from children to professional musicians.\n\nMogees included a range of apps for playful exploration, education, and professional performance. Using one-shot machine learning, the system learned a user's gestures (such as taps, scratches, or rubs) directly on each object and mapped them to sounds, samples, or MIDI parameters in seconds. This allowed every surface to be quickly programmed to respond exactly as the user intended, making instrument creation immediate, personal, and deeply physical.",
    thumbnailVideo: mogeesPro1Video
  },
  {
    id: "mogees-play",
    title: "Mogees Play",
    subtitle: "Product",
    location: "London",
    category: "Products",
    videoUrl: "local:mogees-pro-2",
    description: "Mogees was a hardware sensor and companion app developed between 2013 and 2017 to turn any physical surface of any shape or size into a playable musical instrument. By attaching the sensor to everyday objects, users could transform tables, walls, glass, or metal into expressive, interactive sound interfaces accessible to everyone, from children to professional musicians.\n\nMogees included a range of apps for playful exploration, education, and professional performance. Using one-shot machine learning, the system learned a user's gestures (such as taps, scratches, or rubs) directly on each object and mapped them to sounds, samples, or MIDI parameters in seconds. This allowed every surface to be quickly programmed to respond exactly as the user intended, making instrument creation immediate, personal, and deeply physical.",
    thumbnailVideo: mogeesPro2Video
  },
  {
    id: "mogees-apps",
    title: "Mogees Apps",
    subtitle: "Product",
    location: "London",
    category: "Products",
    videoUrl: "local:mogees-play-apps",
    description: "Mogees was a hardware sensor and companion app developed between 2013 and 2017 to turn any physical surface of any shape or size into a playable musical instrument. By attaching the sensor to everyday objects, users could transform tables, walls, glass, or metal into expressive, interactive sound interfaces accessible to everyone, from children to professional musicians.\n\nMogees included a range of apps for playful exploration, education, and professional performance. Using one-shot machine learning, the system learned a user's gestures (such as taps, scratches, or rubs) directly on each object and mapped them to sounds, samples, or MIDI parameters in seconds. This allowed every surface to be quickly programmed to respond exactly as the user intended, making instrument creation immediate, personal, and deeply physical.",
    thumbnailVideo: mogeesPlayAppsVideo
  },
  {
    id: "playing-stove",
    title: "Stove as Instrument",
    subtitle: "London",
    location: "London",
    category: "Products",
    videoUrl: "https://www.youtube.com/watch?v=_7J6iBd2qVg",
    description: "Demonstration project exploring how a domestic cooking surface can function as a musical interface. Using vibration sensing and real-time signal analysis, taps and gestures on the stove are translated into sound.\n\nPitch selection is handled automatically, removing a common barrier to musical learning. Players instead control tempo, dynamics, articulation, and timbre through touch and gesture, enabling immediate and expressive interaction without prior training.\n\nThe demo investigates how everyday objects, augmented with sensing and algorithms, can support alternative models of musical pedagogy and interaction.",
    thumbnailVideo: stoveVideo
  },
];

export const categories = ["All", "Art", "Installations", "Products"];

export const about = {
  bio: "Bruno Zamborlin, PhD, is an AI researcher and artist, recognized for revolutionizing human-computer interaction through his startups: Mogees, HyperSurfaces, and HyperSentience. His work focuses on transforming everyday objects and surfaces into interactive, intelligent entities, thereby redefining our interaction with the space and between us. Based in London and Milan, Bruno Zamborlin is a four times TEDx speaker and honorary research fellow at Goldsmiths, univ. Of London. His artworks have been showcased at venues like the Venice Biennale and the London Victoria & Albert Museum.",
  practice: "At the core of Zamborlin's work is a keen desire to create connections—whether between friends, strangers, or the spaces that envelop them. By transforming everyday objects and surfaces into interactive canvases, Zamborlin invites participants into a shared experience, turning mundane moments into opportunities for discovery and connection, fostering a sense of community and shared wonder.\n\nZamborlin's work gives voice to the world around us. Through his pioneering application of vibration sensors and algorithms, spaces and objects gain the ability to respond to human touch, movement, and even atmospheric changes, effectively speaking to us in a language of light, sound and data. This interaction blurs the lines between the animate and inanimate, inviting observers to reconsider their relationship with their surroundings.\n\nIn a society increasingly mediated by touchscreens and virtual interfaces, Zamborlin's work is a reminder of the richness of the physical world. By emphasizing tactile engagement and the sensory experiences of the environment and people around us, he offers a counter-narrative to the digital disconnection, rekindling an appreciation for the tangible and fostering a deeper, more meaningful interaction with the world.",
  contact: "b@brunozamborlin.ai"
};

export const technology = {
  videoUrl: "https://www.youtube.com/watch?v=7X9k73HHMyw",
  thumbnailVideo: tedVideo,
  text: [
    "By coupling vibration sensors with specialized algorithms, inanimate objects, surfaces, and entire spaces can be enabled to respond to human touch and atmospheric phenomena in real-time.",
    "The natural acoustics of solid surfaces can be altered so as to produce musical sounds which are always unique, as is every lightest touch, gentle caress, or falling raindrop.",
    "These algorithms can also control lighting and video displays, creating synesthetic experiences of touch, sound and light.",
    "Such data-enabled surfaces open up new possibilities for understanding and engaging with the spaces around us."
  ]
}
